name: Crystal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: crystal build together.cr --release --static
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: together
        path: together
