name: CI

on: 
  push:
    branches:    
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: MeilCli/setup-crystal-action@v3
        with: 
          crystal_version: 0.35.0
      - name: Build
        run: crystal build 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: together
          path: together